### ISSUE TITLE
Using ICU matcher with multiple interpolations will only handle the first interpolation

### ISSUE THREAD

**Issue by anthonkendel** [fkirc/attranslate#131]
**Describe the bug**

As described by the title, when using ICU matcher with multiple interpolations will only handle the first interpolation.

```
npx attranslate --srcFile=path/to/translations/en.json --srcLng=en --srcFormat=nested-json --targetFile sv.json --targetLng=sv --targetFormat=nested-json --matcher=icu --service google-translate
```

Example: 

```json
{
  "pageXofX": "{currentPage} of {numberOfPages}"
}
```

is generated into:

```json
{
  "pageXofX": "{currentPage} av <span> 1 </span>"
}
```

**To Reproduce**

Translate the JSON example above.

**Expected behavior**

The generated file should not change/remove any of the interpolation values, i.e. `{value}`.

**Files**

N/A

**Additional context**

N/A

**Comment by fkirc** [comment]
Thanks for reporting this issue.
Ironically, your example seems to work correctly if I run it with `--matcher=none`.

In fact, I am not even sure whether those matchers are doing a better job than translating everything without matchers.
Because even if something goes wrong with interpolations, `attranslate` should allow quick and simple manual corrections.

Nevertheless, I released 1.5.1 in order to fix your specific issue.
Please let me know if something is still broken with 1.5.1.
